### ISSUE TITLE
impossible to use

### ISSUE THREAD

**Issue by MouMoutMan** [AXN-Informatique/laravel-models-generator#3]
Hi,

After install with composer, when i lauch command `php artisan vendor:publish --tag=models-generator.config` i have this message :
 There are no commands defined in the "vendor" namespace.

i use a lumen 7 project ;)

thx

**Comment by MouMoutMan** [comment]
`php artisan models:generate` displays the same error:   There are no commands defined in the "models" namespace.  

Can you help me or or complete the readme.md plz ?

**Comment by forxer** [comment]
Hello,

This package does not have support for Lumen.

We do not use Lumen internally and have not planned to set it up, however a pull-request would be welcome.
