### ISSUE TITLE
Relations

### ISSUE THREAD

**Issue by blondie63** [AXN-Informatique/laravel-models-generator#4]
Hi, What relationships does cmd "models:generate", does it scan the table fields to see if there are any relationships with other tables?

Thanks

**Comment by forxer** [comment]
@lgtaxn I think you will be able to answer better than me

**Comment by lgtaxn** [comment]
Hi, sorry for the late answer.
Yes, it scans the database schema to find foreign keys constraints and build models relationships according to these constraints (only "belongs to" and "has one or many").

**Comment by forxer** [comment]
Hello @blondie63, without any response from you, I am closing this issue.
