### ISSUE TITLE
Hai，In Laravel  Wrong，I need Help

### ISSUE THREAD

**Issue by lookapu** [AXN-Informatique/laravel-models-generator#6]
Symfony\Component\ErrorHandler\Error\FatalError: Trait 'App\Models\GeneratedRelations\HfUserloginlogRelations' not found in file /www/wwwroot/www.xxx.com/app/Models/HfUserLoginLog.php on line 9

——————

So,  Thank U~

**Comment by forxer** [comment]
Could you show us the top of the generated model file. With the "use ..."

Also, what is the name of the table linked to the model

**Comment by forxer** [comment]
Hello @lookapu , without any response from you, I am closing this issue.
